# Generated by Django 4.0.3 on 2022-03-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mobilenumber',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
